### ISSUE TITLE
Editing not possible

### ISSUE THREAD

**Issue by Kantiran91** [software-competence-center-hagenberg/NodeDoc#2]
Hi,

thank you for the great tool. I think this can help a lot.

I test it locally (mac with docker and safari/firefox) and was not able to edit the document field. 

Do you have any idea why?

**Comment by stefanschoeberl-scch** [comment]
Hi, thank you for the positive feedback!

I just checked the Docker setup and there seemed to have been a misconfiguration regarding the CouchDB port in the docker-compose.yml. I fixed it and now the text editors should work again.

Please try again with the current version. Further, please re-generate any documentation that you have generated so far (delete it with the bin button next to the HTML button, then click on the gear button to generate it again).

Also, please make sure, that the browser does not cache the documentation => reload it with CMD+OPTION+R in Safari.

**Comment by Kantiran91** [comment]
Now it works! Thank you
